//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubOne.PS.CostSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cost", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Cost : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Supplier SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UnitCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Billable {
            get {
                return this.BillableField;
            }
            set {
                if ((object.ReferenceEquals(this.BillableField, value) != true)) {
                    this.BillableField = value;
                    this.RaisePropertyChanged("Billable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        /// <summary>
        /// The Quantity of the Cost
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Supplier Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierIDField, value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnitCost {
            get {
                return this.UnitCostField;
            }
            set {
                if ((this.UnitCostField.Equals(value) != true)) {
                    this.UnitCostField = value;
                    this.RaisePropertyChanged("UnitCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFMBase", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Supplier))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Contact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Client))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Staff))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Job))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Milestone))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Note))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Template))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.WFMResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CostSvc.Cost))]
    public partial class WFMBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameUnformattedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberRecordsRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StartPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsDeletedField, value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameUnformatted {
            get {
                return this.NameUnformattedField;
            }
            set {
                if ((object.ReferenceEquals(this.NameUnformattedField, value) != true)) {
                    this.NameUnformattedField = value;
                    this.RaisePropertyChanged("NameUnformatted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberRecordsRequested {
            get {
                return this.NumberRecordsRequestedField;
            }
            set {
                if ((this.NumberRecordsRequestedField.Equals(value) != true)) {
                    this.NumberRecordsRequestedField = value;
                    this.RaisePropertyChanged("NumberRecordsRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StartPosition {
            get {
                return this.StartPositionField;
            }
            set {
                if ((this.StartPositionField.Equals(value) != true)) {
                    this.StartPositionField = value;
                    this.RaisePropertyChanged("StartPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Supplier : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Contact[] ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsArchivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Note[] NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferralSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Contact[] Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsArchived {
            get {
                return this.IsArchivedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsArchivedField, value) != true)) {
                    this.IsArchivedField = value;
                    this.RaisePropertyChanged("IsArchived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Note[] Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalAddress {
            get {
                return this.PostalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddressField, value) != true)) {
                    this.PostalAddressField = value;
                    this.RaisePropertyChanged("PostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCity {
            get {
                return this.PostalCityField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCityField, value) != true)) {
                    this.PostalCityField = value;
                    this.RaisePropertyChanged("PostalCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCountry {
            get {
                return this.PostalCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCountryField, value) != true)) {
                    this.PostalCountryField = value;
                    this.RaisePropertyChanged("PostalCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalPostCode {
            get {
                return this.PostalPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalPostCodeField, value) != true)) {
                    this.PostalPostCodeField = value;
                    this.RaisePropertyChanged("PostalPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalRegion {
            get {
                return this.PostalRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalRegionField, value) != true)) {
                    this.PostalRegionField = value;
                    this.RaisePropertyChanged("PostalRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferralSource {
            get {
                return this.ReferralSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferralSourceField, value) != true)) {
                    this.ReferralSourceField = value;
                    this.RaisePropertyChanged("ReferralSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Contact : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Supplier SupplierField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressee {
            get {
                return this.AddresseeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseeField, value) != true)) {
                    this.AddresseeField = value;
                    this.RaisePropertyChanged("Addressee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactTypeField, value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Supplier Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Client : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Staff AccountManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgencyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Contact[] ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExportCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GstRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsArchivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsProspectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Note[] NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalRegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrepareGstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryContactAddresseeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryContactMobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryContactSalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferralSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignedTaxAuthorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Staff AccountManager {
            get {
                return this.AccountManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountManagerField, value) != true)) {
                    this.AccountManagerField = value;
                    this.RaisePropertyChanged("AccountManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgencyStatus {
            get {
                return this.AgencyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AgencyStatusField, value) != true)) {
                    this.AgencyStatusField = value;
                    this.RaisePropertyChanged("AgencyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessNumber {
            get {
                return this.BusinessNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessNumberField, value) != true)) {
                    this.BusinessNumberField = value;
                    this.RaisePropertyChanged("BusinessNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyNumber {
            get {
                return this.CompanyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNumberField, value) != true)) {
                    this.CompanyNumberField = value;
                    this.RaisePropertyChanged("CompanyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Contact[] Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExportCode {
            get {
                return this.ExportCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExportCodeField, value) != true)) {
                    this.ExportCodeField = value;
                    this.RaisePropertyChanged("ExportCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GstRegistered {
            get {
                return this.GstRegisteredField;
            }
            set {
                if ((object.ReferenceEquals(this.GstRegisteredField, value) != true)) {
                    this.GstRegisteredField = value;
                    this.RaisePropertyChanged("GstRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsArchived {
            get {
                return this.IsArchivedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsArchivedField, value) != true)) {
                    this.IsArchivedField = value;
                    this.RaisePropertyChanged("IsArchived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsProspect {
            get {
                return this.IsProspectField;
            }
            set {
                if ((object.ReferenceEquals(this.IsProspectField, value) != true)) {
                    this.IsProspectField = value;
                    this.RaisePropertyChanged("IsProspect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Note[] Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalAddress {
            get {
                return this.PostalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddressField, value) != true)) {
                    this.PostalAddressField = value;
                    this.RaisePropertyChanged("PostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCity {
            get {
                return this.PostalCityField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCityField, value) != true)) {
                    this.PostalCityField = value;
                    this.RaisePropertyChanged("PostalCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCountry {
            get {
                return this.PostalCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCountryField, value) != true)) {
                    this.PostalCountryField = value;
                    this.RaisePropertyChanged("PostalCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalPostCode {
            get {
                return this.PostalPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalPostCodeField, value) != true)) {
                    this.PostalPostCodeField = value;
                    this.RaisePropertyChanged("PostalPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalRegion {
            get {
                return this.PostalRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalRegionField, value) != true)) {
                    this.PostalRegionField = value;
                    this.RaisePropertyChanged("PostalRegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrepareGst {
            get {
                return this.PrepareGstField;
            }
            set {
                if ((object.ReferenceEquals(this.PrepareGstField, value) != true)) {
                    this.PrepareGstField = value;
                    this.RaisePropertyChanged("PrepareGst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryContactAddressee {
            get {
                return this.PrimaryContactAddresseeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryContactAddresseeField, value) != true)) {
                    this.PrimaryContactAddresseeField = value;
                    this.RaisePropertyChanged("PrimaryContactAddressee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryContactEmail {
            get {
                return this.PrimaryContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryContactEmailField, value) != true)) {
                    this.PrimaryContactEmailField = value;
                    this.RaisePropertyChanged("PrimaryContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryContactMobile {
            get {
                return this.PrimaryContactMobileField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryContactMobileField, value) != true)) {
                    this.PrimaryContactMobileField = value;
                    this.RaisePropertyChanged("PrimaryContactMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryContactName {
            get {
                return this.PrimaryContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryContactNameField, value) != true)) {
                    this.PrimaryContactNameField = value;
                    this.RaisePropertyChanged("PrimaryContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryContactPhone {
            get {
                return this.PrimaryContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryContactPhoneField, value) != true)) {
                    this.PrimaryContactPhoneField = value;
                    this.RaisePropertyChanged("PrimaryContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryContactSalutation {
            get {
                return this.PrimaryContactSalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryContactSalutationField, value) != true)) {
                    this.PrimaryContactSalutationField = value;
                    this.RaisePropertyChanged("PrimaryContactSalutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferralSource {
            get {
                return this.ReferralSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferralSourceField, value) != true)) {
                    this.ReferralSourceField = value;
                    this.RaisePropertyChanged("ReferralSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignedTaxAuthority {
            get {
                return this.SignedTaxAuthorityField;
            }
            set {
                if ((object.ReferenceEquals(this.SignedTaxAuthorityField, value) != true)) {
                    this.SignedTaxAuthorityField = value;
                    this.RaisePropertyChanged("SignedTaxAuthority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaxNumber {
            get {
                return this.TaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TaxNumberField, value) != true)) {
                    this.TaxNumberField = value;
                    this.RaisePropertyChanged("TaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Staff : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Job[] JobsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayrollCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Security SecurityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Job[] Jobs {
            get {
                return this.JobsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobsField, value) != true)) {
                    this.JobsField = value;
                    this.RaisePropertyChanged("Jobs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayrollCode {
            get {
                return this.PayrollCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PayrollCodeField, value) != true)) {
                    this.PayrollCodeField = value;
                    this.RaisePropertyChanged("PayrollCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Security Security {
            get {
                return this.SecurityField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityField, value) != true)) {
                    this.SecurityField = value;
                    this.RaisePropertyChanged("Security");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Job : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Staff[] AssignedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Document[] DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Staff ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Milestone[] MilestonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Note[] NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Task[] TasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Template[] TemplatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Staff[] Assigned {
            get {
                return this.AssignedField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedField, value) != true)) {
                    this.AssignedField = value;
                    this.RaisePropertyChanged("Assigned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIDField, value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientNumber {
            get {
                return this.ClientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNumberField, value) != true)) {
                    this.ClientNumberField = value;
                    this.RaisePropertyChanged("ClientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactID {
            get {
                return this.ContactIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactIDField, value) != true)) {
                    this.ContactIDField = value;
                    this.RaisePropertyChanged("ContactID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Document[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalID {
            get {
                return this.InternalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InternalIDField, value) != true)) {
                    this.InternalIDField = value;
                    this.RaisePropertyChanged("InternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Staff Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Milestone[] Milestones {
            get {
                return this.MilestonesField;
            }
            set {
                if ((object.ReferenceEquals(this.MilestonesField, value) != true)) {
                    this.MilestonesField = value;
                    this.RaisePropertyChanged("Milestones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Note[] Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskMode {
            get {
                return this.TaskModeField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskModeField, value) != true)) {
                    this.TaskModeField = value;
                    this.RaisePropertyChanged("TaskMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Task[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateID {
            get {
                return this.TemplateIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateIDField, value) != true)) {
                    this.TemplateIDField = value;
                    this.RaisePropertyChanged("TemplateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Template[] Templates {
            get {
                return this.TemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatesField, value) != true)) {
                    this.TemplatesField = value;
                    this.RaisePropertyChanged("Templates");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Document : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedByField, value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Public {
            get {
                return this.PublicField;
            }
            set {
                if ((this.PublicField.Equals(value) != true)) {
                    this.PublicField = value;
                    this.RaisePropertyChanged("Public");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Milestone", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Milestone : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Public {
            get {
                return this.PublicField;
            }
            set {
                if ((this.PublicField.Equals(value) != true)) {
                    this.PublicField = value;
                    this.RaisePropertyChanged("Public");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Note", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Note : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder {
            get {
                return this.FolderField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderField, value) != true)) {
                    this.FolderField = value;
                    this.RaisePropertyChanged("Folder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Public {
            get {
                return this.PublicField;
            }
            set {
                if ((this.PublicField.Equals(value) != true)) {
                    this.PublicField = value;
                    this.RaisePropertyChanged("Public");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Task : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstimatedMinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DueDateField, value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstimatedMinutes {
            get {
                return this.EstimatedMinutesField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimatedMinutesField, value) != true)) {
                    this.EstimatedMinutesField = value;
                    this.RaisePropertyChanged("EstimatedMinutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskIDField, value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Template", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Template : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CostSvc.Job _jobField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CostSvc.Job _job {
            get {
                return this._jobField;
            }
            set {
                if ((object.ReferenceEquals(this._jobField, value) != true)) {
                    this._jobField = value;
                    this.RaisePropertyChanged("_job");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFMResponse", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class WFMResponse : HubOne.PS.CostSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescription1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ErrorDescription")]
        public string ErrorDescription1 {
            get {
                return this.ErrorDescription1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescription1Field, value) != true)) {
                    this.ErrorDescription1Field = value;
                    this.RaisePropertyChanged("ErrorDescription1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Status")]
        public string Status1 {
            get {
                return this.Status1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Status1Field, value) != true)) {
                    this.Status1Field = value;
                    this.RaisePropertyChanged("Status1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Security", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Security : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CostSvc.ICost")]
    public interface ICost {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/ClearCacheOfType", ReplyAction="http://tempuri.org/ICost/ClearCacheOfTypeResponse")]
        void ClearCacheOfType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/ClearCacheOfType", ReplyAction="http://tempuri.org/ICost/ClearCacheOfTypeResponse")]
        System.Threading.Tasks.Task ClearCacheOfTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/GetAllCosts", ReplyAction="http://tempuri.org/ICost/GetAllCostsResponse")]
        HubOne.PS.CostSvc.Cost[] GetAllCosts(string accountKey, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/GetAllCosts", ReplyAction="http://tempuri.org/ICost/GetAllCostsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost[]> GetAllCostsAsync(string accountKey, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/GetAllCostsPaged", ReplyAction="http://tempuri.org/ICost/GetAllCostsPagedResponse")]
        HubOne.PS.CostSvc.Cost[] GetAllCostsPaged(string accountKey, int page, System.Nullable<int> startPosition, int recordCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/GetAllCostsPaged", ReplyAction="http://tempuri.org/ICost/GetAllCostsPagedResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost[]> GetAllCostsPagedAsync(string accountKey, int page, System.Nullable<int> startPosition, int recordCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/GetCost", ReplyAction="http://tempuri.org/ICost/GetCostResponse")]
        HubOne.PS.CostSvc.Cost GetCost(string costID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/GetCost", ReplyAction="http://tempuri.org/ICost/GetCostResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost> GetCostAsync(string costID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/AddCost", ReplyAction="http://tempuri.org/ICost/AddCostResponse")]
        HubOne.PS.CostSvc.Cost AddCost(HubOne.PS.CostSvc.Cost cost, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/AddCost", ReplyAction="http://tempuri.org/ICost/AddCostResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost> AddCostAsync(HubOne.PS.CostSvc.Cost cost, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/UpdateCost", ReplyAction="http://tempuri.org/ICost/UpdateCostResponse")]
        HubOne.PS.CostSvc.Cost UpdateCost(HubOne.PS.CostSvc.Cost cost, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/UpdateCost", ReplyAction="http://tempuri.org/ICost/UpdateCostResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost> UpdateCostAsync(HubOne.PS.CostSvc.Cost cost, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/DeleteCost", ReplyAction="http://tempuri.org/ICost/DeleteCostResponse")]
        HubOne.PS.CostSvc.WFMResponse DeleteCost(HubOne.PS.CostSvc.Cost cost, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/DeleteCost", ReplyAction="http://tempuri.org/ICost/DeleteCostResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.WFMResponse> DeleteCostAsync(HubOne.PS.CostSvc.Cost cost, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/DeleteAllCosts", ReplyAction="http://tempuri.org/ICost/DeleteAllCostsResponse")]
        HubOne.PS.CostSvc.WFMResponse DeleteAllCosts(string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICost/DeleteAllCosts", ReplyAction="http://tempuri.org/ICost/DeleteAllCostsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CostSvc.WFMResponse> DeleteAllCostsAsync(string accountKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICostChannel : HubOne.PS.CostSvc.ICost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CostClient : System.ServiceModel.ClientBase<HubOne.PS.CostSvc.ICost>, HubOne.PS.CostSvc.ICost {
        
        public CostClient() {
        }
        
        public CostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClearCacheOfType() {
            base.Channel.ClearCacheOfType();
        }
        
        public System.Threading.Tasks.Task ClearCacheOfTypeAsync() {
            return base.Channel.ClearCacheOfTypeAsync();
        }
        
        public HubOne.PS.CostSvc.Cost[] GetAllCosts(string accountKey, int page) {
            return base.Channel.GetAllCosts(accountKey, page);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost[]> GetAllCostsAsync(string accountKey, int page) {
            return base.Channel.GetAllCostsAsync(accountKey, page);
        }
        
        public HubOne.PS.CostSvc.Cost[] GetAllCostsPaged(string accountKey, int page, System.Nullable<int> startPosition, int recordCount) {
            return base.Channel.GetAllCostsPaged(accountKey, page, startPosition, recordCount);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost[]> GetAllCostsPagedAsync(string accountKey, int page, System.Nullable<int> startPosition, int recordCount) {
            return base.Channel.GetAllCostsPagedAsync(accountKey, page, startPosition, recordCount);
        }
        
        public HubOne.PS.CostSvc.Cost GetCost(string costID, string accountKey) {
            return base.Channel.GetCost(costID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost> GetCostAsync(string costID, string accountKey) {
            return base.Channel.GetCostAsync(costID, accountKey);
        }
        
        public HubOne.PS.CostSvc.Cost AddCost(HubOne.PS.CostSvc.Cost cost, string accountKey) {
            return base.Channel.AddCost(cost, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost> AddCostAsync(HubOne.PS.CostSvc.Cost cost, string accountKey) {
            return base.Channel.AddCostAsync(cost, accountKey);
        }
        
        public HubOne.PS.CostSvc.Cost UpdateCost(HubOne.PS.CostSvc.Cost cost, string accountKey) {
            return base.Channel.UpdateCost(cost, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.Cost> UpdateCostAsync(HubOne.PS.CostSvc.Cost cost, string accountKey) {
            return base.Channel.UpdateCostAsync(cost, accountKey);
        }
        
        public HubOne.PS.CostSvc.WFMResponse DeleteCost(HubOne.PS.CostSvc.Cost cost, string accountKey) {
            return base.Channel.DeleteCost(cost, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.WFMResponse> DeleteCostAsync(HubOne.PS.CostSvc.Cost cost, string accountKey) {
            return base.Channel.DeleteCostAsync(cost, accountKey);
        }
        
        public HubOne.PS.CostSvc.WFMResponse DeleteAllCosts(string accountKey) {
            return base.Channel.DeleteAllCosts(accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CostSvc.WFMResponse> DeleteAllCostsAsync(string accountKey) {
            return base.Channel.DeleteAllCostsAsync(accountKey);
        }
    }
}
