//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubOne.PS.TimeSvc {
    using System.Runtime.Serialization;
    using System;
    
    /// <summary>
    /// Represents a WorkflowMax Time Object
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Time", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Time : HubOne.PS.TimeSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BillableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskField;
        
        /// <summary>
        /// Gets or sets the Billable property of the time object
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Billable {
            get {
                return this.BillableField;
            }
            set {
                if ((this.BillableField.Equals(value) != true)) {
                    this.BillableField = value;
                    this.RaisePropertyChanged("Billable");
                }
            }
        }
        
        /// <summary>
        /// The Date of the TS Entry
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string End {
            get {
                return this.EndField;
            }
            set {
                if ((object.ReferenceEquals(this.EndField, value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Minutes {
            get {
                return this.MinutesField;
            }
            set {
                if ((this.MinutesField.Equals(value) != true)) {
                    this.MinutesField = value;
                    this.RaisePropertyChanged("Minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Start {
            get {
                return this.StartField;
            }
            set {
                if ((object.ReferenceEquals(this.StartField, value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFMBase", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.TimeSvc.Timesheet))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.TimeSvc.WFMResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.TimeSvc.Time))]
    public partial class WFMBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberRecordsRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StartPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsDeletedField, value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberRecordsRequested {
            get {
                return this.NumberRecordsRequestedField;
            }
            set {
                if ((this.NumberRecordsRequestedField.Equals(value) != true)) {
                    this.NumberRecordsRequestedField = value;
                    this.RaisePropertyChanged("NumberRecordsRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StartPosition {
            get {
                return this.StartPositionField;
            }
            set {
                if ((this.StartPositionField.Equals(value) != true)) {
                    this.StartPositionField = value;
                    this.RaisePropertyChanged("StartPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timesheet", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Timesheet : HubOne.PS.TimeSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BillableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Billable {
            get {
                return this.BillableField;
            }
            set {
                if ((this.BillableField.Equals(value) != true)) {
                    this.BillableField = value;
                    this.RaisePropertyChanged("Billable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string End {
            get {
                return this.EndField;
            }
            set {
                if ((object.ReferenceEquals(this.EndField, value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Minutes {
            get {
                return this.MinutesField;
            }
            set {
                if ((this.MinutesField.Equals(value) != true)) {
                    this.MinutesField = value;
                    this.RaisePropertyChanged("Minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Staff {
            get {
                return this.StaffField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffField, value) != true)) {
                    this.StaffField = value;
                    this.RaisePropertyChanged("Staff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Start {
            get {
                return this.StartField;
            }
            set {
                if ((object.ReferenceEquals(this.StartField, value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Task {
            get {
                return this.TaskField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskField, value) != true)) {
                    this.TaskField = value;
                    this.RaisePropertyChanged("Task");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFMResponse", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class WFMResponse : HubOne.PS.TimeSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescription1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ErrorDescription")]
        public string ErrorDescription1 {
            get {
                return this.ErrorDescription1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescription1Field, value) != true)) {
                    this.ErrorDescription1Field = value;
                    this.RaisePropertyChanged("ErrorDescription1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Status")]
        public string Status1 {
            get {
                return this.Status1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Status1Field, value) != true)) {
                    this.Status1Field = value;
                    this.RaisePropertyChanged("Status1");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeSvc.ITime")]
    public interface ITime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/ClearCacheOfType", ReplyAction="http://tempuri.org/ITime/ClearCacheOfTypeResponse")]
        void ClearCacheOfType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/GetJobTimeSheets", ReplyAction="http://tempuri.org/ITime/GetJobTimeSheetsResponse")]
        HubOne.PS.TimeSvc.Time[] GetJobTimeSheets(string jobID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/GetAllTimeSheets", ReplyAction="http://tempuri.org/ITime/GetAllTimeSheetsResponse")]
        HubOne.PS.TimeSvc.Time[] GetAllTimeSheets(string accountKey, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/GetAllTimeSheetsPaged", ReplyAction="http://tempuri.org/ITime/GetAllTimeSheetsPagedResponse")]
        HubOne.PS.TimeSvc.Time[] GetAllTimeSheetsPaged(string accountKey, System.DateTime dateFrom, System.DateTime dateTo, System.Nullable<int> startPosition, int recordCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/GetStaffTimeSheets", ReplyAction="http://tempuri.org/ITime/GetStaffTimeSheetsResponse")]
        HubOne.PS.TimeSvc.Time[] GetStaffTimeSheets(string staffID, System.DateTime dateFrom, System.DateTime dateTo, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/GetTimeSheet", ReplyAction="http://tempuri.org/ITime/GetTimeSheetResponse")]
        HubOne.PS.TimeSvc.Time GetTimeSheet(string timeID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/AddJobTimeSheet", ReplyAction="http://tempuri.org/ITime/AddJobTimeSheetResponse")]
        HubOne.PS.TimeSvc.Time AddJobTimeSheet(HubOne.PS.TimeSvc.Timesheet timeSheet, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/UpdateJobTimeSheet", ReplyAction="http://tempuri.org/ITime/UpdateJobTimeSheetResponse")]
        HubOne.PS.TimeSvc.Time UpdateJobTimeSheet(HubOne.PS.TimeSvc.Timesheet timeSheet, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITime/DeleteTimeSheet", ReplyAction="http://tempuri.org/ITime/DeleteTimeSheetResponse")]
        HubOne.PS.TimeSvc.WFMResponse DeleteTimeSheet(string timeSheetID, string accountKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeChannel : HubOne.PS.TimeSvc.ITime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeClient : System.ServiceModel.ClientBase<HubOne.PS.TimeSvc.ITime>, HubOne.PS.TimeSvc.ITime {
        
        public TimeClient() {
        }
        
        public TimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClearCacheOfType() {
            base.Channel.ClearCacheOfType();
        }
        
        public HubOne.PS.TimeSvc.Time[] GetJobTimeSheets(string jobID, string accountKey) {
            return base.Channel.GetJobTimeSheets(jobID, accountKey);
        }
        
        public HubOne.PS.TimeSvc.Time[] GetAllTimeSheets(string accountKey, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.GetAllTimeSheets(accountKey, dateFrom, dateTo);
        }
        
        public HubOne.PS.TimeSvc.Time[] GetAllTimeSheetsPaged(string accountKey, System.DateTime dateFrom, System.DateTime dateTo, System.Nullable<int> startPosition, int recordCount) {
            return base.Channel.GetAllTimeSheetsPaged(accountKey, dateFrom, dateTo, startPosition, recordCount);
        }
        
        public HubOne.PS.TimeSvc.Time[] GetStaffTimeSheets(string staffID, System.DateTime dateFrom, System.DateTime dateTo, string accountKey) {
            return base.Channel.GetStaffTimeSheets(staffID, dateFrom, dateTo, accountKey);
        }
        
        public HubOne.PS.TimeSvc.Time GetTimeSheet(string timeID, string accountKey) {
            return base.Channel.GetTimeSheet(timeID, accountKey);
        }
        
        public HubOne.PS.TimeSvc.Time AddJobTimeSheet(HubOne.PS.TimeSvc.Timesheet timeSheet, string accountKey) {
            return base.Channel.AddJobTimeSheet(timeSheet, accountKey);
        }
        
        public HubOne.PS.TimeSvc.Time UpdateJobTimeSheet(HubOne.PS.TimeSvc.Timesheet timeSheet, string accountKey) {
            return base.Channel.UpdateJobTimeSheet(timeSheet, accountKey);
        }
        
        public HubOne.PS.TimeSvc.WFMResponse DeleteTimeSheet(string timeSheetID, string accountKey) {
            return base.Channel.DeleteTimeSheet(timeSheetID, accountKey);
        }
    }
}
