//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubOne.PS.CustomFieldSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFieldDefinition", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class CustomFieldDefinition : HubOne.PS.CustomFieldSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HubOne.PS.CustomFieldSvc.Option[] OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] OptionsValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseLeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UseSupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueElementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkUrl {
            get {
                return this.LinkUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkUrlField, value) != true)) {
                    this.LinkUrlField = value;
                    this.RaisePropertyChanged("LinkUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HubOne.PS.CustomFieldSvc.Option[] Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] OptionsValues {
            get {
                return this.OptionsValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsValuesField, value) != true)) {
                    this.OptionsValuesField = value;
                    this.RaisePropertyChanged("OptionsValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseClient {
            get {
                return this.UseClientField;
            }
            set {
                if ((this.UseClientField.Equals(value) != true)) {
                    this.UseClientField = value;
                    this.RaisePropertyChanged("UseClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseContact {
            get {
                return this.UseContactField;
            }
            set {
                if ((this.UseContactField.Equals(value) != true)) {
                    this.UseContactField = value;
                    this.RaisePropertyChanged("UseContact");
                }
            }
        }
        
        /// <summary>
        /// Whether ot use the Job or Not
        /// </summary>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseJob {
            get {
                return this.UseJobField;
            }
            set {
                if ((this.UseJobField.Equals(value) != true)) {
                    this.UseJobField = value;
                    this.RaisePropertyChanged("UseJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseLead {
            get {
                return this.UseLeadField;
            }
            set {
                if ((this.UseLeadField.Equals(value) != true)) {
                    this.UseLeadField = value;
                    this.RaisePropertyChanged("UseLead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseSupplier {
            get {
                return this.UseSupplierField;
            }
            set {
                if ((this.UseSupplierField.Equals(value) != true)) {
                    this.UseSupplierField = value;
                    this.RaisePropertyChanged("UseSupplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueElement {
            get {
                return this.ValueElementField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueElementField, value) != true)) {
                    this.ValueElementField = value;
                    this.RaisePropertyChanged("ValueElement");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFMBase", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CustomFieldSvc.Option))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CustomFieldSvc.CustomField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CustomFieldSvc.WFMResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HubOne.PS.CustomFieldSvc.CustomFieldDefinition))]
    public partial class WFMBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameUnformattedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberRecordsRequestedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StartPositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDescription {
            get {
                return this.ErrorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescriptionField, value) != true)) {
                    this.ErrorDescriptionField = value;
                    this.RaisePropertyChanged("ErrorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((object.ReferenceEquals(this.IsDeletedField, value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameUnformatted {
            get {
                return this.NameUnformattedField;
            }
            set {
                if ((object.ReferenceEquals(this.NameUnformattedField, value) != true)) {
                    this.NameUnformattedField = value;
                    this.RaisePropertyChanged("NameUnformatted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumberRecordsRequested {
            get {
                return this.NumberRecordsRequestedField;
            }
            set {
                if ((this.NumberRecordsRequestedField.Equals(value) != true)) {
                    this.NumberRecordsRequestedField = value;
                    this.RaisePropertyChanged("NumberRecordsRequested");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StartPosition {
            get {
                return this.StartPositionField;
            }
            set {
                if ((this.StartPositionField.Equals(value) != true)) {
                    this.StartPositionField = value;
                    this.RaisePropertyChanged("StartPosition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Option", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class Option : HubOne.PS.CustomFieldSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountIncludingTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UnitCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double UnitPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AmountIncludingTax {
            get {
                return this.AmountIncludingTaxField;
            }
            set {
                if ((this.AmountIncludingTaxField.Equals(value) != true)) {
                    this.AmountIncludingTaxField = value;
                    this.RaisePropertyChanged("AmountIncludingTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AmountTax {
            get {
                return this.AmountTaxField;
            }
            set {
                if ((this.AmountTaxField.Equals(value) != true)) {
                    this.AmountTaxField = value;
                    this.RaisePropertyChanged("AmountTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnitCost {
            get {
                return this.UnitCostField;
            }
            set {
                if ((this.UnitCostField.Equals(value) != true)) {
                    this.UnitCostField = value;
                    this.RaisePropertyChanged("UnitCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomField", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class CustomField : HubOne.PS.CustomFieldSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BooleanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DecimalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueElementField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Boolean {
            get {
                return this.BooleanField;
            }
            set {
                if ((this.BooleanField.Equals(value) != true)) {
                    this.BooleanField = value;
                    this.RaisePropertyChanged("Boolean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Decimal {
            get {
                return this.DecimalField;
            }
            set {
                if ((this.DecimalField.Equals(value) != true)) {
                    this.DecimalField = value;
                    this.RaisePropertyChanged("Decimal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueElement {
            get {
                return this.ValueElementField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueElementField, value) != true)) {
                    this.ValueElementField = value;
                    this.RaisePropertyChanged("ValueElement");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WFMResponse", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowMAXService.WFMDataTypes")]
    [System.SerializableAttribute()]
    public partial class WFMResponse : HubOne.PS.CustomFieldSvc.WFMBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDescription1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ErrorDescription")]
        public string ErrorDescription1 {
            get {
                return this.ErrorDescription1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDescription1Field, value) != true)) {
                    this.ErrorDescription1Field = value;
                    this.RaisePropertyChanged("ErrorDescription1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Status")]
        public string Status1 {
            get {
                return this.Status1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Status1Field, value) != true)) {
                    this.Status1Field = value;
                    this.RaisePropertyChanged("Status1");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomFieldSvc.ICustomFieldDefinition")]
    public interface ICustomFieldDefinition {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/ClearCacheOfType", ReplyAction="http://tempuri.org/ICustomFieldDefinition/ClearCacheOfTypeResponse")]
        void ClearCacheOfType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/ClearCacheOfType", ReplyAction="http://tempuri.org/ICustomFieldDefinition/ClearCacheOfTypeResponse")]
        System.Threading.Tasks.Task ClearCacheOfTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitions", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitionsResponse")]
        HubOne.PS.CustomFieldSvc.CustomFieldDefinition[] GetAllCustomFieldDefinitions(string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitions", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitionsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomFieldDefinition[]> GetAllCustomFieldDefinitionsAsync(string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitionsPaged", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitionsPagedRespon" +
            "se")]
        HubOne.PS.CustomFieldSvc.CustomFieldDefinition[] GetAllCustomFieldDefinitionsPaged(string accountKey, string customFieldDefinitionID, System.Nullable<int> startPosition, int recordCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitionsPaged", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetAllCustomFieldDefinitionsPagedRespon" +
            "se")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomFieldDefinition[]> GetAllCustomFieldDefinitionsPagedAsync(string accountKey, string customFieldDefinitionID, System.Nullable<int> startPosition, int recordCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetClientCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetClientCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetClientCustomFields(string clientID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetClientCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetClientCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetClientCustomFieldsAsync(string clientID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetContactCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetContactCustomFields(string contactID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetContactCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetContactCustomFieldsAsync(string contactID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetSupplierCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetSupplierCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetSupplierCustomFields(string supplierID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetSupplierCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetSupplierCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetSupplierCustomFieldsAsync(string supplierID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetSupplierContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetSupplierContactCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetSupplierContactCustomFields(string supplierContactID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetSupplierContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetSupplierContactCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetSupplierContactCustomFieldsAsync(string supplierContactID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetJobCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetJobCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetJobCustomFields(string jobID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetJobCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetJobCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetJobCustomFieldsAsync(string jobID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetJobTaskCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetJobTaskCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetJobTaskCustomFields(string jobTaskID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetJobTaskCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetJobTaskCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetJobTaskCustomFieldsAsync(string jobTaskID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetJobCostCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetJobCostCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetJobCostCustomFields(string jobCostID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetJobCostCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetJobCostCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetJobCostCustomFieldsAsync(string jobCostID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetTimeCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetTimeCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetTimeCustomFields(string timeID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetTimeCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetTimeCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetTimeCustomFieldsAsync(string timeID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetLeadCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetLeadCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.CustomField[] GetLeadCustomFields(string leadID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/GetLeadCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/GetLeadCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetLeadCustomFieldsAsync(string leadID, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateClientCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateClientCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateClientCustomFields(string clientID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateClientCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateClientCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateClientCustomFieldsAsync(string clientID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateContactCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateContactCustomFields(string contactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateContactCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateContactCustomFieldsAsync(string contactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateSupplierCustomFields(string supplierID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateSupplierCustomFieldsAsync(string supplierID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierContactCustomFieldsRespon" +
            "se")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateSupplierContactCustomFields(string supplierContactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierContactCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateSupplierContactCustomFieldsRespon" +
            "se")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateSupplierContactCustomFieldsAsync(string supplierContactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateJobCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateJobCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateJobCustomFields(string jobID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateJobCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateJobCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateJobCustomFieldsAsync(string jobID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateJobTaskCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateJobTaskCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateJobTaskCustomFields(string jobTaskID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateJobTaskCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateJobTaskCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateJobTaskCustomFieldsAsync(string jobTaskID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateJobCostCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateJobCostCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateJobCostCustomFields(string jobCostID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateJobCostCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateJobCostCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateJobCostCustomFieldsAsync(string jobCostID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateTimeCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateTimeCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateTimeCustomFields(string timeID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateTimeCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateTimeCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateTimeCustomFieldsAsync(string timeID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateLeadCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateLeadCustomFieldsResponse")]
        HubOne.PS.CustomFieldSvc.WFMResponse UpdateLeadCustomFields(string leadID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomFieldDefinition/UpdateLeadCustomFields", ReplyAction="http://tempuri.org/ICustomFieldDefinition/UpdateLeadCustomFieldsResponse")]
        System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateLeadCustomFieldsAsync(string leadID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomFieldDefinitionChannel : HubOne.PS.CustomFieldSvc.ICustomFieldDefinition, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomFieldDefinitionClient : System.ServiceModel.ClientBase<HubOne.PS.CustomFieldSvc.ICustomFieldDefinition>, HubOne.PS.CustomFieldSvc.ICustomFieldDefinition {
        
        public CustomFieldDefinitionClient() {
        }
        
        public CustomFieldDefinitionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomFieldDefinitionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomFieldDefinitionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomFieldDefinitionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ClearCacheOfType() {
            base.Channel.ClearCacheOfType();
        }
        
        public System.Threading.Tasks.Task ClearCacheOfTypeAsync() {
            return base.Channel.ClearCacheOfTypeAsync();
        }
        
        public HubOne.PS.CustomFieldSvc.CustomFieldDefinition[] GetAllCustomFieldDefinitions(string accountKey) {
            return base.Channel.GetAllCustomFieldDefinitions(accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomFieldDefinition[]> GetAllCustomFieldDefinitionsAsync(string accountKey) {
            return base.Channel.GetAllCustomFieldDefinitionsAsync(accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomFieldDefinition[] GetAllCustomFieldDefinitionsPaged(string accountKey, string customFieldDefinitionID, System.Nullable<int> startPosition, int recordCount) {
            return base.Channel.GetAllCustomFieldDefinitionsPaged(accountKey, customFieldDefinitionID, startPosition, recordCount);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomFieldDefinition[]> GetAllCustomFieldDefinitionsPagedAsync(string accountKey, string customFieldDefinitionID, System.Nullable<int> startPosition, int recordCount) {
            return base.Channel.GetAllCustomFieldDefinitionsPagedAsync(accountKey, customFieldDefinitionID, startPosition, recordCount);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetClientCustomFields(string clientID, string accountKey) {
            return base.Channel.GetClientCustomFields(clientID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetClientCustomFieldsAsync(string clientID, string accountKey) {
            return base.Channel.GetClientCustomFieldsAsync(clientID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetContactCustomFields(string contactID, string accountKey) {
            return base.Channel.GetContactCustomFields(contactID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetContactCustomFieldsAsync(string contactID, string accountKey) {
            return base.Channel.GetContactCustomFieldsAsync(contactID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetSupplierCustomFields(string supplierID, string accountKey) {
            return base.Channel.GetSupplierCustomFields(supplierID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetSupplierCustomFieldsAsync(string supplierID, string accountKey) {
            return base.Channel.GetSupplierCustomFieldsAsync(supplierID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetSupplierContactCustomFields(string supplierContactID, string accountKey) {
            return base.Channel.GetSupplierContactCustomFields(supplierContactID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetSupplierContactCustomFieldsAsync(string supplierContactID, string accountKey) {
            return base.Channel.GetSupplierContactCustomFieldsAsync(supplierContactID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetJobCustomFields(string jobID, string accountKey) {
            return base.Channel.GetJobCustomFields(jobID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetJobCustomFieldsAsync(string jobID, string accountKey) {
            return base.Channel.GetJobCustomFieldsAsync(jobID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetJobTaskCustomFields(string jobTaskID, string accountKey) {
            return base.Channel.GetJobTaskCustomFields(jobTaskID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetJobTaskCustomFieldsAsync(string jobTaskID, string accountKey) {
            return base.Channel.GetJobTaskCustomFieldsAsync(jobTaskID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetJobCostCustomFields(string jobCostID, string accountKey) {
            return base.Channel.GetJobCostCustomFields(jobCostID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetJobCostCustomFieldsAsync(string jobCostID, string accountKey) {
            return base.Channel.GetJobCostCustomFieldsAsync(jobCostID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetTimeCustomFields(string timeID, string accountKey) {
            return base.Channel.GetTimeCustomFields(timeID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetTimeCustomFieldsAsync(string timeID, string accountKey) {
            return base.Channel.GetTimeCustomFieldsAsync(timeID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.CustomField[] GetLeadCustomFields(string leadID, string accountKey) {
            return base.Channel.GetLeadCustomFields(leadID, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.CustomField[]> GetLeadCustomFieldsAsync(string leadID, string accountKey) {
            return base.Channel.GetLeadCustomFieldsAsync(leadID, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateClientCustomFields(string clientID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateClientCustomFields(clientID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateClientCustomFieldsAsync(string clientID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateClientCustomFieldsAsync(clientID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateContactCustomFields(string contactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateContactCustomFields(contactID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateContactCustomFieldsAsync(string contactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateContactCustomFieldsAsync(contactID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateSupplierCustomFields(string supplierID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateSupplierCustomFields(supplierID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateSupplierCustomFieldsAsync(string supplierID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateSupplierCustomFieldsAsync(supplierID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateSupplierContactCustomFields(string supplierContactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateSupplierContactCustomFields(supplierContactID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateSupplierContactCustomFieldsAsync(string supplierContactID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateSupplierContactCustomFieldsAsync(supplierContactID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateJobCustomFields(string jobID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateJobCustomFields(jobID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateJobCustomFieldsAsync(string jobID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateJobCustomFieldsAsync(jobID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateJobTaskCustomFields(string jobTaskID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateJobTaskCustomFields(jobTaskID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateJobTaskCustomFieldsAsync(string jobTaskID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateJobTaskCustomFieldsAsync(jobTaskID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateJobCostCustomFields(string jobCostID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateJobCostCustomFields(jobCostID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateJobCostCustomFieldsAsync(string jobCostID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateJobCostCustomFieldsAsync(jobCostID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateTimeCustomFields(string timeID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateTimeCustomFields(timeID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateTimeCustomFieldsAsync(string timeID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateTimeCustomFieldsAsync(timeID, customFields, accountKey);
        }
        
        public HubOne.PS.CustomFieldSvc.WFMResponse UpdateLeadCustomFields(string leadID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateLeadCustomFields(leadID, customFields, accountKey);
        }
        
        public System.Threading.Tasks.Task<HubOne.PS.CustomFieldSvc.WFMResponse> UpdateLeadCustomFieldsAsync(string leadID, HubOne.PS.CustomFieldSvc.CustomField[] customFields, string accountKey) {
            return base.Channel.UpdateLeadCustomFieldsAsync(leadID, customFields, accountKey);
        }
    }
}
